export const LANDING = '/';
export const SIGN_UP = '/signup';
export const SIGN_IN = '/signin';
export const HOME = '/home';
export const ACCOUNT = '/account';
export const ADMIN = '/admin';
export const PASSWORD_FORGET = '/pw-forget';
export const COURIER_HOME ="/courier-home"
export const SUCCESSFUL_ORDER = "/successful-order"
export const DELIVERY_FORM = "/delivery-form"
export const CUSTOMER_DASHBOARD = "/customer-dashboard"
export const CONFIRM_DELIVERY = "/confirm-delivery?"